/**
 * CANONICAL WORKFLOW ACTION REGISTRY
 *
 * SSoT cho toàn bộ các Canonical Workflow Actions trong PQM.
 * Tuyệt đối chỉ sử dụng 8 Canonical Roles (ADMIN, QA, QC, LAB, PRODUCTION, USER, VIEWER, GUEST).
 */

import { WorkflowActionId, WorkflowActionMetadata } from '../contracts/actions';

export const CANONICAL_ACTION_REGISTRY: Record<WorkflowActionId, WorkflowActionMetadata> = {
  // --- BATCH DOMAIN ---
  BATCH_CREATE: {
    actionId: 'BATCH_CREATE',
    entityType: 'BATCH',
    category: 'LIFECYCLE',
    description: 'Tạo mới hồ sơ Lô sản xuất (luôn khởi tạo ở trạng thái PENDING)',
    allowedRoles: ['ADMIN', 'PRODUCTION', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'BatchStateMachine',
  },
  BATCH_UPDATE_METADATA: {
    actionId: 'BATCH_UPDATE_METADATA',
    entityType: 'BATCH',
    category: 'LIFECYCLE',
    description: 'Cập nhật thông tin mô tả, sản lượng thực tế, hạn dùng của Lô',
    allowedRoles: ['ADMIN', 'PRODUCTION', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'BatchStateMachine',
  },
  BATCH_DISPATCH_TESTING: {
    actionId: 'BATCH_DISPATCH_TESTING',
    entityType: 'BATCH',
    category: 'TRANSITION',
    description: 'Chuyển Lô sản xuất sang trạng thái đang kiểm nghiệm (TESTING)',
    allowedRoles: ['ADMIN', 'PRODUCTION', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'BatchStateMachine',
  },
  BATCH_EVALUATE_RELEASE: {
    actionId: 'BATCH_EVALUATE_RELEASE',
    entityType: 'BATCH',
    category: 'QUALITY',
    description: 'Đánh giá điều kiện xuất xưởng Lô qua 7 Release Gates',
    allowedRoles: ['ADMIN', 'QA', 'QC'],
    risk: 'HIGH',
    requiresAudit: false,
    requiresReason: false,
  },
  BATCH_RELEASE_APPROVE: {
    actionId: 'BATCH_RELEASE_APPROVE',
    entityType: 'BATCH',
    category: 'APPROVAL',
    description: 'QA ký duyệt xuất xưởng Lô sản phẩm đạt chuẩn ra thị trường (RELEASED)',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    requiresSignature: true,
    targetFsm: 'BatchStateMachine',
  },
  BATCH_REJECT: {
    actionId: 'BATCH_REJECT',
    entityType: 'BATCH',
    category: 'APPROVAL',
    description: 'QA từ chối xuất xưởng Lô do vi phạm tiêu chuẩn chất lượng (REJECTED)',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresSignature: true,
    targetFsm: 'BatchStateMachine',
  },
  BATCH_HOLD: {
    actionId: 'BATCH_HOLD',
    entityType: 'BATCH',
    category: 'GOVERNANCE',
    description: 'Tạm giữ Lô sản xuất phục vụ thanh tra hoặc điều tra OOS/CAPA',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    targetFsm: 'BatchStateMachine',
  },
  BATCH_RECALL: {
    actionId: 'BATCH_RECALL',
    entityType: 'BATCH',
    category: 'GOVERNANCE',
    description: 'Thu hồi khẩn cấp Lô đã phát hành trên thị trường',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresSignature: true,
    targetFsm: 'BatchStateMachine',
  },
  BATCH_DELETE: {
    actionId: 'BATCH_DELETE',
    entityType: 'BATCH',
    category: 'ADMIN',
    description: 'Xóa hồ sơ Lô rác chưa qua kiểm nghiệm (chỉ Admin)',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresTypedConfirmation: true,
    expectedConfirmationToken: 'CONFIRM-DELETE-BATCH',
  },

  // --- TEST RESULT DOMAIN ---
  TEST_RESULT_CREATE: {
    actionId: 'TEST_RESULT_CREATE',
    entityType: 'TEST_RESULT',
    category: 'LIFECYCLE',
    description: 'Khởi tạo phiếu kiểm nghiệm mới theo tiêu chuẩn TCCS hiệu lực',
    allowedRoles: ['ADMIN', 'QC', 'LAB', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'TestResultWorkflowStateMachine',
  },
  TEST_RESULT_ENTRY_INPUT: {
    actionId: 'TEST_RESULT_ENTRY_INPUT',
    entityType: 'TEST_RESULT',
    category: 'QUALITY',
    description: 'Nhập giá trị đo lường và đánh giá chỉ tiêu phân tích',
    allowedRoles: ['ADMIN', 'QC', 'LAB', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'TestResultWorkflowStateMachine',
  },
  TEST_RESULT_CALCULATION_RUN: {
    actionId: 'TEST_RESULT_CALCULATION_RUN',
    entityType: 'TEST_RESULT',
    category: 'QUALITY',
    description: 'Thực thi bộ máy đánh giá chất lượng tất định (QualityEvaluationEngine)',
    allowedRoles: ['ADMIN', 'LAB', 'QA', 'QC'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
  TEST_RESULT_SUBMIT: {
    actionId: 'TEST_RESULT_SUBMIT',
    entityType: 'TEST_RESULT',
    category: 'TRANSITION',
    description: 'Kiểm nghiệm viên nộp phiếu kiểm nghiệm chờ soát xét và phê duyệt',
    allowedRoles: ['ADMIN', 'QC', 'LAB', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'TestResultWorkflowStateMachine',
  },
  TEST_RESULT_APPROVE: {
    actionId: 'TEST_RESULT_APPROVE',
    entityType: 'TEST_RESULT',
    category: 'APPROVAL',
    description: 'QA phê duyệt và niêm phong phiếu kiểm nghiệm (EvaluationSnapshot SHA-256)',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    requiresSignature: false,
    targetFsm: 'TestResultWorkflowStateMachine',
  },
  TEST_RESULT_REJECT: {
    actionId: 'TEST_RESULT_REJECT',
    entityType: 'TEST_RESULT',
    category: 'APPROVAL',
    description: 'QA từ chối phiếu kiểm nghiệm, yêu cầu kiểm nghiệm lại',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    targetFsm: 'TestResultWorkflowStateMachine',
  },
  TEST_RESULT_CANCEL: {
    actionId: 'TEST_RESULT_CANCEL',
    entityType: 'TEST_RESULT',
    category: 'TRANSITION',
    description: 'Hủy phiếu kiểm nghiệm chưa duyệt do sự cố mẫu hoặc nhập nhầm',
    allowedRoles: ['ADMIN', 'LAB', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: true,
    targetFsm: 'TestResultWorkflowStateMachine',
  },
  TEST_RESULT_REVOKE: {
    actionId: 'TEST_RESULT_REVOKE',
    entityType: 'TEST_RESULT',
    category: 'GOVERNANCE',
    description: 'Thu hồi phiếu kiểm nghiệm đã duyệt (yêu cầu lý do và chữ ký số QA)',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresSignature: true,
    targetFsm: 'TestResultWorkflowStateMachine',
  },
  TEST_RESULT_REEVALUATE: {
    actionId: 'TEST_RESULT_REEVALUATE',
    entityType: 'TEST_RESULT',
    category: 'QUALITY',
    description: 'Tái thẩm định niêm phong snapshot khi có hiệu chỉnh TCCS có kiểm soát',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  TEST_RESULT_DELETE: {
    actionId: 'TEST_RESULT_DELETE',
    entityType: 'TEST_RESULT',
    category: 'ADMIN',
    description: 'Xóa phiếu kiểm nghiệm nháp chưa ghi nhận (chỉ Admin)',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },

  // --- DEVIATION & OOS DOMAIN ---
  DEVIATION_CREATE: {
    actionId: 'DEVIATION_CREATE',
    entityType: 'DEVIATION',
    category: 'LIFECYCLE',
    description: 'Khởi tạo hồ sơ ghi nhận sai lệch chất lượng mới',
    allowedRoles: ['ADMIN', 'QC', 'QA', 'LAB', 'PRODUCTION'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'DeviationStateMachine',
  },
  DEVIATION_INVESTIGATE: {
    actionId: 'DEVIATION_INVESTIGATE',
    entityType: 'DEVIATION',
    category: 'QUALITY',
    description: 'Nhập báo cáo điều tra nguyên nhân gốc rễ (RCA, 5 Whys)',
    allowedRoles: ['ADMIN', 'QC', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'DeviationStateMachine',
  },
  DEVIATION_APPROVE: {
    actionId: 'DEVIATION_APPROVE',
    entityType: 'DEVIATION',
    category: 'APPROVAL',
    description: 'QA phê duyệt kết luận điều tra và biện pháp xử lý sai lệch',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    requiresSignature: true,
    targetFsm: 'DeviationStateMachine',
  },
  DEVIATION_CLOSE: {
    actionId: 'DEVIATION_CLOSE',
    entityType: 'DEVIATION',
    category: 'TRANSITION',
    description: 'Đóng hồ sơ sai lệch sau khi hoàn thành 100% biện pháp khắc phục',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    targetFsm: 'DeviationStateMachine',
  },
  DEVIATION_DELETE: {
    actionId: 'DEVIATION_DELETE',
    entityType: 'DEVIATION',
    category: 'ADMIN',
    description: 'Xóa hồ sơ sai lệch nhập nhầm (chỉ Admin + lý do bắt buộc)',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  OOS_CREATE: {
    actionId: 'OOS_CREATE',
    entityType: 'OOS',
    category: 'LIFECYCLE',
    description: 'Kích hoạt hồ sơ điều tra kết quả ngoài tiêu chuẩn OOS',
    allowedRoles: ['ADMIN', 'QC', 'QA', 'LAB'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
  },
  OOS_PHASE1_LAB_INVESTIGATE: {
    actionId: 'OOS_PHASE1_LAB_INVESTIGATE',
    entityType: 'OOS',
    category: 'QUALITY',
    description: 'Thực hiện điều tra giai đoạn 1 tại phòng kiểm nghiệm (Lab Error)',
    allowedRoles: ['ADMIN', 'QC', 'QA', 'LAB'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
  },
  OOS_PHASE2_MFG_INVESTIGATE: {
    actionId: 'OOS_PHASE2_MFG_INVESTIGATE',
    entityType: 'OOS',
    category: 'QUALITY',
    description: 'Thực hiện điều tra giai đoạn 2 tại xưởng sản xuất (Manufacturing Error)',
    allowedRoles: ['ADMIN', 'QA', 'PRODUCTION'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
  },
  OOS_CONCLUDE: {
    actionId: 'OOS_CONCLUDE',
    entityType: 'OOS',
    category: 'APPROVAL',
    description: 'Kết luận điều tra OOS và xác định phương án xử lý lô',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresSignature: true,
  },

  // --- CAPA DOMAIN ---
  CAPA_CREATE: {
    actionId: 'CAPA_CREATE',
    entityType: 'CAPA',
    category: 'LIFECYCLE',
    description: 'Khởi tạo hồ sơ hành động khắc phục & phòng ngừa (CAPA)',
    allowedRoles: ['ADMIN', 'QA', 'QC'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'CapaStateMachine',
  },
  CAPA_ASSIGN: {
    actionId: 'CAPA_ASSIGN',
    entityType: 'CAPA',
    category: 'TRANSITION',
    description: 'Phân công nhân sự và thời hạn thực hiện hành động CAPA',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'CapaStateMachine',
  },
  CAPA_EXECUTE: {
    actionId: 'CAPA_EXECUTE',
    entityType: 'CAPA',
    category: 'TRANSITION',
    description: 'Ghi nhận kết quả triển khai hành động khắc phục/phòng ngừa',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'PRODUCTION', 'LAB'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'CapaStateMachine',
  },
  CAPA_VERIFY: {
    actionId: 'CAPA_VERIFY',
    entityType: 'CAPA',
    category: 'APPROVAL',
    description: 'QA thẩm tra và xác nhận tính hiệu quả của biện pháp CAPA',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'CapaStateMachine',
  },
  CAPA_CLOSE: {
    actionId: 'CAPA_CLOSE',
    entityType: 'CAPA',
    category: 'TRANSITION',
    description: 'QA chính thức đóng hồ sơ CAPA sau khi thẩm tra thành công',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresSignature: true,
    targetFsm: 'CapaStateMachine',
  },

  // --- CHANGE CONTROL DOMAIN ---
  CHANGE_REQUEST_CREATE: {
    actionId: 'CHANGE_REQUEST_CREATE',
    entityType: 'CHANGE_REQUEST',
    category: 'LIFECYCLE',
    description: 'Khởi tạo đề xuất kiểm soát thay đổi mới (CR-YYYY-XXXX)',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'PRODUCTION', 'USER'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'ChangeControlStateMachine',
  },
  CHANGE_REQUEST_FMEA_ASSESS: {
    actionId: 'CHANGE_REQUEST_FMEA_ASSESS',
    entityType: 'CHANGE_REQUEST',
    category: 'QUALITY',
    description: 'Đánh giá ma trận rủi ro FMEA (Severity x Occurrence x Detection = RPN)',
    allowedRoles: ['ADMIN', 'QA', 'QC'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'ChangeControlStateMachine',
  },
  CHANGE_REQUEST_ADD_ACTION: {
    actionId: 'CHANGE_REQUEST_ADD_ACTION',
    entityType: 'CHANGE_REQUEST',
    category: 'LIFECYCLE',
    description: 'Bổ sung hành động vào kế hoạch triển khai thay đổi',
    allowedRoles: ['ADMIN', 'QA', 'PRODUCTION'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  CHANGE_REQUEST_COMPLETE_ACTION: {
    actionId: 'CHANGE_REQUEST_COMPLETE_ACTION',
    entityType: 'CHANGE_REQUEST',
    category: 'TRANSITION',
    description: 'Xác nhận hoàn tất một hành động trong kế hoạch thay đổi',
    allowedRoles: ['ADMIN', 'QA', 'PRODUCTION', 'LAB', 'USER'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  CHANGE_REQUEST_REVIEW: {
    actionId: 'CHANGE_REQUEST_REVIEW',
    entityType: 'CHANGE_REQUEST',
    category: 'APPROVAL',
    description: 'Hội đồng chuyên môn soát xét đánh giá tác động thay đổi',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'ChangeControlStateMachine',
  },
  CHANGE_REQUEST_APPROVE: {
    actionId: 'CHANGE_REQUEST_APPROVE',
    entityType: 'CHANGE_REQUEST',
    category: 'APPROVAL',
    description: 'QA phê duyệt cho phép triển khai kế hoạch thay đổi',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    requiresSignature: true,
    targetFsm: 'ChangeControlStateMachine',
  },
  CHANGE_REQUEST_REJECT: {
    actionId: 'CHANGE_REQUEST_REJECT',
    entityType: 'CHANGE_REQUEST',
    category: 'APPROVAL',
    description: 'QA từ chối yêu cầu thay đổi do rủi ro GMP không thể kiểm soát',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    targetFsm: 'ChangeControlStateMachine',
  },
  CHANGE_REQUEST_IMPLEMENT: {
    actionId: 'CHANGE_REQUEST_IMPLEMENT',
    entityType: 'CHANGE_REQUEST',
    category: 'TRANSITION',
    description: 'Bắt đầu giai đoạn triển khai kế hoạch thay đổi trong thực tế',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'ChangeControlStateMachine',
  },
  CHANGE_REQUEST_CLOSE: {
    actionId: 'CHANGE_REQUEST_CLOSE',
    entityType: 'CHANGE_REQUEST',
    category: 'TRANSITION',
    description: 'QA đóng hồ sơ thay đổi khi 100% hành động đã hoàn tất và thẩm tra',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresSignature: true,
    targetFsm: 'ChangeControlStateMachine',
  },

  // --- APPROVAL, COA & E-SIGNATURE DOMAIN ---
  APPROVAL_TASK_CREATE: {
    actionId: 'APPROVAL_TASK_CREATE',
    entityType: 'APPROVAL_TASK',
    category: 'LIFECYCLE',
    description: 'Khởi tạo nhiệm vụ phê duyệt liên kết thực thể (Batch, TestResult, TCCS)',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'LAB', 'PRODUCTION'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'ApprovalTaskStateMachine',
  },
  APPROVAL_TASK_DECIDE: {
    actionId: 'APPROVAL_TASK_DECIDE',
    entityType: 'APPROVAL_TASK',
    category: 'APPROVAL',
    description: 'Người có thẩm quyền quyết định Phê duyệt / Từ chối kèm Chữ ký số CFR Part 11',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'PRODUCTION'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    requiresSignature: false,
    targetFsm: 'ApprovalTaskStateMachine',
  },
  APPROVAL_TASK_CANCEL: {
    actionId: 'APPROVAL_TASK_CANCEL',
    entityType: 'APPROVAL_TASK',
    category: 'TRANSITION',
    description: 'Hủy nhiệm vụ phê duyệt khi kế hoạch hoặc thực thể liên kết thay đổi',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: true,
    targetFsm: 'ApprovalTaskStateMachine',
  },
  COA_GENERATE: {
    actionId: 'COA_GENERATE',
    entityType: 'COA',
    category: 'DOCUMENT',
    description: 'Sinh phiếu phân tích thành phẩm từ locked EvaluationSnapshot',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'LAB', 'USER'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
  },
  COA_SIGN: {
    actionId: 'COA_SIGN',
    entityType: 'COA',
    category: 'APPROVAL',
    description: 'QA ký số ban hành chứng chỉ CoA điện tử có mã QR xác thực',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    requiresSignature: true,
  },
  COA_REVOKE: {
    actionId: 'COA_REVOKE',
    entityType: 'COA',
    category: 'GOVERNANCE',
    description: 'Thu hồi hiệu lực chứng nhận CoA đã ban hành do phát hiện sai lệch',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresSignature: true,
  },
  COA_VERIFY_PUBLIC: {
    actionId: 'COA_VERIFY_PUBLIC',
    entityType: 'COA',
    category: 'DOCUMENT',
    description: 'Truy vấn xác thực công khai mã QR chứng chỉ CoA (Read-Only)',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'LAB', 'PRODUCTION', 'USER', 'VIEWER', 'GUEST'],
    risk: 'NONE',
    requiresAudit: false,
    requiresReason: false,
  },

  // --- MASTER DATA DOMAIN ---
  PRODUCT_CREATE: {
    actionId: 'PRODUCT_CREATE',
    entityType: 'PRODUCT',
    category: 'LIFECYCLE',
    description: 'Tạo mới hồ sơ sản phẩm',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  PRODUCT_UPDATE: {
    actionId: 'PRODUCT_UPDATE',
    entityType: 'PRODUCT',
    category: 'LIFECYCLE',
    description: 'Cập nhật thông tin hồ sơ sản phẩm',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: true,
  },
  PRODUCT_ARCHIVE: {
    actionId: 'PRODUCT_ARCHIVE',
    entityType: 'PRODUCT',
    category: 'LIFECYCLE',
    description: 'Lưu trữ/vô hiệu hóa sản phẩm không còn kinh doanh',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  MATERIAL_CREATE: {
    actionId: 'MATERIAL_CREATE',
    entityType: 'MATERIAL',
    category: 'LIFECYCLE',
    description: 'Tạo mới nguyên phụ liệu',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  MATERIAL_UPDATE: {
    actionId: 'MATERIAL_UPDATE',
    entityType: 'MATERIAL',
    category: 'LIFECYCLE',
    description: 'Cập nhật thông tin nguyên phụ liệu',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: true,
  },
  MATERIAL_DELETE: {
    actionId: 'MATERIAL_DELETE',
    entityType: 'MATERIAL',
    category: 'LIFECYCLE',
    description: 'Xóa nguyên phụ liệu chưa được sử dụng trong công thức',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  TCCS_CREATE: {
    actionId: 'TCCS_CREATE',
    entityType: 'TCCS',
    category: 'LIFECYCLE',
    description: 'Tạo mới hồ sơ Tiêu chuẩn cơ sở (TCCS)',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'TccsStateMachine',
  },
  TCCS_UPDATE_DRAFT: {
    actionId: 'TCCS_UPDATE_DRAFT',
    entityType: 'TCCS',
    category: 'LIFECYCLE',
    description: 'Hiệu chỉnh bản nháp chỉ tiêu và quy tắc thay thế của TCCS',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'TccsStateMachine',
  },
  TCCS_SUBMIT: {
    actionId: 'TCCS_SUBMIT',
    entityType: 'TCCS',
    category: 'TRANSITION',
    description: 'Trình duyệt hồ sơ TCCS',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    targetFsm: 'TccsStateMachine',
  },
  TCCS_APPROVE: {
    actionId: 'TCCS_APPROVE',
    entityType: 'TCCS',
    category: 'APPROVAL',
    description: 'QA phê duyệt ban hành TCCS chính thức (chuyển sang ACTIVE)',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
    requiresSignature: true,
    targetFsm: 'TccsStateMachine',
  },
  TCCS_REVISE: {
    actionId: 'TCCS_REVISE',
    entityType: 'TCCS',
    category: 'LIFECYCLE',
    description: 'Tạo phiên bản sửa đổi (Revision) cho TCCS đã ban hành',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    targetFsm: 'TccsStateMachine',
  },
  TCCS_OBSOLETE: {
    actionId: 'TCCS_OBSOLETE',
    entityType: 'TCCS',
    category: 'GOVERNANCE',
    description: 'Ngừng áp dụng tiêu chuẩn cơ sở cũ',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    targetFsm: 'TccsStateMachine',
  },
  FORMULA_CREATE: {
    actionId: 'FORMULA_CREATE',
    entityType: 'FORMULA',
    category: 'LIFECYCLE',
    description: 'Tạo mới công thức sản phẩm',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: false,
  },
  FORMULA_UPDATE: {
    actionId: 'FORMULA_UPDATE',
    entityType: 'FORMULA',
    category: 'LIFECYCLE',
    description: 'Cập nhật thành phần và hàm lượng trong công thức',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  FORMULA_ARCHIVE: {
    actionId: 'FORMULA_ARCHIVE',
    entityType: 'FORMULA',
    category: 'LIFECYCLE',
    description: 'Lưu trữ công thức cũ không còn sản xuất',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  CRITERIA_MASTER_CREATE: {
    actionId: 'CRITERIA_MASTER_CREATE',
    entityType: 'MASTER_DATA',
    category: 'LIFECYCLE',
    description: 'Tạo mới chỉ tiêu chuẩn hóa Master Criterion',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  CRITERIA_MASTER_UPDATE: {
    actionId: 'CRITERIA_MASTER_UPDATE',
    entityType: 'MASTER_DATA',
    category: 'LIFECYCLE',
    description: 'Cập nhật tên hoặc phân loại chỉ tiêu Master Criterion',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: true,
  },
  CRITERIA_ALIAS_MAP: {
    actionId: 'CRITERIA_ALIAS_MAP',
    entityType: 'MASTER_DATA',
    category: 'LIFECYCLE',
    description: 'Ánh xạ tên viết tắt/OCR với chỉ tiêu chuẩn hóa',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  LAB_MASTER_CREATE: {
    actionId: 'LAB_MASTER_CREATE',
    entityType: 'MASTER_DATA',
    category: 'LIFECYCLE',
    description: 'Đăng ký đơn vị kiểm nghiệm mới (Testing Laboratory)',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'LOW',
    requiresAudit: true,
    requiresReason: false,
  },
  LAB_MASTER_UPDATE: {
    actionId: 'LAB_MASTER_UPDATE',
    entityType: 'MASTER_DATA',
    category: 'LIFECYCLE',
    description: 'Cập nhật thông tin đơn vị kiểm nghiệm',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'LOW',
    requiresAudit: true,
    requiresReason: false,
  },
  PHARMACOPOEIA_CREATE: {
    actionId: 'PHARMACOPOEIA_CREATE',
    entityType: 'MASTER_DATA',
    category: 'LIFECYCLE',
    description: 'Thêm mới tiêu chuẩn Dược điển động',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  PHARMACOPOEIA_UPDATE: {
    actionId: 'PHARMACOPOEIA_UPDATE',
    entityType: 'MASTER_DATA',
    category: 'LIFECYCLE',
    description: 'Cập nhật chỉ tiêu tiêu chuẩn Dược điển',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: true,
  },
  PHARMACOPOEIA_DELETE: {
    actionId: 'PHARMACOPOEIA_DELETE',
    entityType: 'MASTER_DATA',
    category: 'LIFECYCLE',
    description: 'Xóa tiêu chuẩn Dược điển không còn áp dụng',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },

  // --- SYSTEM & INTEGRATION DOMAIN ---
  SYSTEM_BACKUP_EXECUTE: {
    actionId: 'SYSTEM_BACKUP_EXECUTE',
    entityType: 'SYSTEM',
    category: 'ADMIN',
    description: 'Sao lưu cơ sở dữ liệu hệ thống PQM',
    allowedRoles: ['ADMIN'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  SYSTEM_RESTORE_EXECUTE: {
    actionId: 'SYSTEM_RESTORE_EXECUTE',
    entityType: 'SYSTEM',
    category: 'ADMIN',
    description: 'Phục hồi dữ liệu từ bản sao lưu (yêu cầu token xác nhận)',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresTypedConfirmation: true,
    expectedConfirmationToken: 'CONFIRM-RESTORE-DATABASE',
  },
  SYSTEM_WIPE_DEMO_EXECUTE: {
    actionId: 'SYSTEM_WIPE_DEMO_EXECUTE',
    entityType: 'SYSTEM',
    category: 'ADMIN',
    description: 'Xóa toàn bộ dữ liệu mẫu / demo (yêu cầu token xác nhận kép)',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
    requiresTypedConfirmation: true,
    expectedConfirmationToken: 'CONFIRM-WIPE-DEMO-DATA',
  },
  SYSTEM_AUTO_HEAL_PROPOSE: {
    actionId: 'SYSTEM_AUTO_HEAL_PROPOSE',
    entityType: 'SYSTEM',
    category: 'ADMIN',
    description: 'Hệ thống/AI đề xuất phương án hàn gắn tính toàn vẹn',
    allowedRoles: ['ADMIN', 'SYSTEM', 'AI_ADVISORY'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
  SYSTEM_AUTO_HEAL_APPROVE: {
    actionId: 'SYSTEM_AUTO_HEAL_APPROVE',
    entityType: 'SYSTEM',
    category: 'ADMIN',
    description: 'QA/Admin phê duyệt kế hoạch hàn gắn dữ liệu',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  SYSTEM_AUTO_HEAL_EXECUTE: {
    actionId: 'SYSTEM_AUTO_HEAL_EXECUTE',
    entityType: 'SYSTEM',
    category: 'ADMIN',
    description: 'Thực thi giao dịch hàn gắn nguyên tử có rollback handler',
    allowedRoles: ['ADMIN', 'SYSTEM'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  SYSTEM_CONFIG_UPDATE: {
    actionId: 'SYSTEM_CONFIG_UPDATE',
    entityType: 'SYSTEM',
    category: 'ADMIN',
    description: 'Cập nhật cấu hình hệ thống (Google Drive, Gemini API, v.v.)',
    allowedRoles: ['ADMIN'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: true,
  },
  SYSTEM_USER_ROLE_ASSIGN: {
    actionId: 'SYSTEM_USER_ROLE_ASSIGN',
    entityType: 'SYSTEM',
    category: 'ADMIN',
    description: 'Phân quyền vai trò tài khoản người dùng',
    allowedRoles: ['ADMIN'],
    risk: 'HIGH',
    requiresAudit: true,
    requiresReason: true,
  },
  FILE_STORAGE_UPLOAD: {
    actionId: 'FILE_STORAGE_UPLOAD',
    entityType: 'SYSTEM',
    category: 'DOCUMENT',
    description: 'Tải file đính kèm lên Firebase Storage',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'LAB', 'PRODUCTION', 'USER'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: false,
  },
  FILE_STORAGE_DELETE: {
    actionId: 'FILE_STORAGE_DELETE',
    entityType: 'SYSTEM',
    category: 'DOCUMENT',
    description: 'Xóa file đính kèm trên Firebase Storage',
    allowedRoles: ['ADMIN', 'QA'],
    risk: 'MEDIUM',
    requiresAudit: true,
    requiresReason: true,
  },
  EXCEL_DATA_EXPORT: {
    actionId: 'EXCEL_DATA_EXPORT',
    entityType: 'SYSTEM',
    category: 'DOCUMENT',
    description: 'Xuất dữ liệu hệ thống ra file Excel',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'LAB', 'PRODUCTION', 'USER', 'VIEWER'],
    risk: 'LOW',
    requiresAudit: true,
    requiresReason: false,
  },
  CLOUD_FUNCTION_INVOKE: {
    actionId: 'CLOUD_FUNCTION_INVOKE',
    entityType: 'SYSTEM',
    category: 'QUALITY',
    description: 'Gọi hàm tính toán Cloud Function (SPC, Cron, Trigger)',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'SYSTEM'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },

  // --- AI ADVISORY DOMAIN ---
  AI_OCR_EXTRACT: {
    actionId: 'AI_OCR_EXTRACT',
    entityType: 'TEST_RESULT',
    category: 'QUALITY',
    description: 'Trích xuất OCR kết quả kiểm nghiệm từ PDF nhiều trang (Advisory)',
    allowedRoles: ['ADMIN', 'LAB', 'QA', 'AI_ADVISORY'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
  AI_MAPPING_PROPOSE: {
    actionId: 'AI_MAPPING_PROPOSE',
    entityType: 'MASTER_DATA',
    category: 'QUALITY',
    description: 'Đề xuất ánh xạ tên chỉ tiêu tự học (AI Proposal only)',
    allowedRoles: ['ADMIN', 'LAB', 'QA', 'AI_ADVISORY'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
  AI_STABILITY_PREDICT: {
    actionId: 'AI_STABILITY_PREDICT',
    entityType: 'BATCH',
    category: 'QUALITY',
    description: 'Dự báo động học suy giảm hạn dùng ICH Q1A (Advisory calculation)',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'AI_ADVISORY'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
  AI_BATCH_CLEARANCE_PROPOSE: {
    actionId: 'AI_BATCH_CLEARANCE_PROPOSE',
    entityType: 'BATCH',
    category: 'QUALITY',
    description: 'Trợ lý AI soát xét hồ sơ lô và đề xuất khuyến nghị QA (Proposal only)',
    allowedRoles: ['ADMIN', 'QA', 'AI_ADVISORY'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
  AI_NATURAL_QUERY: {
    actionId: 'AI_NATURAL_QUERY',
    entityType: 'SYSTEM',
    category: 'GOVERNANCE',
    description: 'Truy vấn giải thích dữ liệu ngôn ngữ tự nhiên NLP (Read-only)',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'LAB', 'PRODUCTION', 'USER', 'VIEWER', 'AI_ADVISORY'],
    risk: 'NONE',
    requiresAudit: false,
    requiresReason: false,
  },
  AI_VOICE_PARSE: {
    actionId: 'AI_VOICE_PARSE',
    entityType: 'TEST_RESULT',
    category: 'QUALITY',
    description: 'Nhận diện giọng nói nhập liệu kết quả kiểm nghiệm (Advisory)',
    allowedRoles: ['ADMIN', 'LAB', 'QA', 'AI_ADVISORY'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
  AI_LAB_COMPARE: {
    actionId: 'AI_LAB_COMPARE',
    entityType: 'TEST_RESULT',
    category: 'QUALITY',
    description: 'So sánh song song 2 phiếu kiểm nghiệm và đánh giá độ lệch Lab Bias',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'AI_ADVISORY'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
  AI_DATA_INTEGRITY_SCAN: {
    actionId: 'AI_DATA_INTEGRITY_SCAN',
    entityType: 'SYSTEM',
    category: 'GOVERNANCE',
    description: 'Quét và chấm điểm toàn vẹn dữ liệu ALCOA+ Data Integrity Score',
    allowedRoles: ['ADMIN', 'QA', 'QC', 'AI_ADVISORY'],
    risk: 'LOW',
    requiresAudit: false,
    requiresReason: false,
  },
};
